pipeline {
    agent any 
    stages {
        stage('clean install') { 
            steps {
                dir("maven-sample/demo-proj"){
			bat "mvn clean install"
                }
                    
            }
        }
   }
}