INSERT INTO CNTRY_RPT_LIST_INTL (CRLI_CNTRY_IDFR,CNTRY_IDFR,CRLI_CNTRY_NAME,CRLI_CNTRY_NAME_SC,CRLI_CRS_RPTD,CRLI_CRS_CNTRY_PHONE_CODE,CRLI_END_DATE,CRLI_EFCTV_DATE,CRUD_VALUE,CRLI_USER_ID,CRLI_WS_ID,CRLI_LOCAL_TS,CRLI_HOST_TS,RULE_SYSTEM_ID,LDBID,CRLI_ACPT_TS,CRLI_ACPT_TS_UTC_OFST,UUID) 
VALUES(10002760010001,123,'Italy','123','Yes','+39',NULL,'2001-01-01','C','FactoryuserINTL','SYSDATA_INTL',${CURRENTTIMESTAMP},${CURRENTTIMESTAMP},'IntlFactory_countryextn',2800,${CURRENTTIMESTAMP},'+00:00',NULL);

INSERT INTO CNTRY_RPT_LIST_INTL (CRLI_CNTRY_IDFR,CNTRY_IDFR,CRLI_CNTRY_NAME,CRLI_CNTRY_NAME_SC,CRLI_CRS_RPTD,CRLI_CRS_CNTRY_PHONE_CODE,CRLI_END_DATE,CRLI_EFCTV_DATE,CRUD_VALUE,CRLI_USER_ID,CRLI_WS_ID,CRLI_LOCAL_TS,CRLI_HOST_TS,RULE_SYSTEM_ID,LDBID,CRLI_ACPT_TS,CRLI_ACPT_TS_UTC_OFST,UUID) 
VALUES(10002760010002,15,'France','15','Yes','+33',NULL,'2001-01-01','C','FactoryuserINTL','SYSDATA_INTL',${CURRENTTIMESTAMP},${CURRENTTIMESTAMP},'IntlFactory_countryextn',2800,${CURRENTTIMESTAMP},'+00:00',NULL);

INSERT INTO CNTRY_RPT_LIST_INTL (CRLI_CNTRY_IDFR,CNTRY_IDFR,CRLI_CNTRY_NAME,CRLI_CNTRY_NAME_SC,CRLI_CRS_RPTD,CRLI_CRS_CNTRY_PHONE_CODE,CRLI_END_DATE,CRLI_EFCTV_DATE,CRUD_VALUE,CRLI_USER_ID,CRLI_WS_ID,CRLI_LOCAL_TS,CRLI_HOST_TS,RULE_SYSTEM_ID,LDBID,CRLI_ACPT_TS,CRLI_ACPT_TS_UTC_OFST,UUID) 
VALUES(10002760010003,158,'Monaco','15','Yes','+377',NULL,'2001-01-01','C','FactoryuserINTL','SYSDATA_INTL',${CURRENTTIMESTAMP},${CURRENTTIMESTAMP},'IntlFactory_countryextn',2800,${CURRENTTIMESTAMP},'+00:00',NULL);
	