CREATE TABLE CNTRY_RPT_LIST_INTL
	(	
	CRLI_CNTRY_IDFR NUMERIC(15) NOT NULL,
	CNTRY_IDFR NUMERIC(15) NOT NULL,
	CRLI_CNTRY_NAME VARCHAR(120) NOT NULL, 
	CRLI_CNTRY_NAME_SC VARCHAR(120) NOT NULL, 
	CRLI_CRS_RPTD CHAR(4) NOT NULL, 
	CRLI_CRS_CNTRY_PHONE_CODE VARCHAR(4) NOT NULL,
	CRLI_END_DATE DATE,	
	CRLI_EFCTV_DATE DATE NOT NULL,
    CRUD_VALUE  CHAR(1) NOT NULL,
    CRLI_USER_ID VARCHAR(32) NOT NULL, 
	CRLI_WS_ID VARCHAR(32) NOT NULL, 
	CRLI_LOCAL_TS TIMESTAMP (6) NOT NULL, 
	CRLI_HOST_TS TIMESTAMP (6) NOT NULL, 
	RULE_SYSTEM_ID VARCHAR(128) NOT NULL, 
	LDBID NUMERIC(6) NOT NULL, 
	CRLI_ACPT_TS TIMESTAMP (6) NOT NULL, 
	CRLI_ACPT_TS_UTC_OFST CHAR(6) NOT NULL, 
	UUID VARCHAR(36)
   );
  
CREATE UNIQUE INDEX XCRLI01 ON CNTRY_RPT_LIST_INTL
(LDBID ASC
,CRLI_CNTRY_IDFR ASC
,CRLI_EFCTV_DATE DESC
,CRLI_HOST_TS DESC);