FROM openjdk:8-jdk-alpine
COPY spring-boot-liveness-readiness-0.0.1-SNAPSHOT.jar spring-boot-liveness-readiness-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","spring-boot-liveness-readiness-0.0.1-SNAPSHOT.jar"]