# Default values for basic-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: praveen12rajan/spring-boot
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

probe:
    enabled: true
    timeoutSeconds: 5
    readiness:
      path: /actuator/health/readiness
      initialDelaySeconds: 30
      periodSeconds: 30
    liveness:
      path: /actuator/health/liveness
      initialDelaySeconds: 300
      periodSeconds: 600
