//const logger = require('./WinstonLog');
//const logger = require('./PinoLog');
//const logger = require('./BunyanLog');
const logger = require('./Log4JsLog');

logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');
logger.info('log to file');
logger.error('Error happened');

