connection:
    pool:
        max_size: 20
        timeout: 1800
logging:
    level:
      com:
        demo: DEBUG
      org:
        springframework: ERROR
    pattern:
      console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
      file: "%d %p %c{1.} [%t] %m%n"
    file: app.log
spring:
    cache:
        type: simple
    datasource:
        driver-class-name: org.postgresql.Driver
        pwd: User@1234
        testWhileIdle: 'true '
        url: jdbc:postgresql://localhost:5432/demo
        username: demo_user
        validationQuery: SELECT 1 from dual
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        generate-ddl: false
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
        show-sql: true