server:
  servlet:
    context-path: /api
spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
  profiles:
    active: dev
token:
  secret: Xkx2axHkZIqVMFUfZRriBg==
  expiry:
    key: ":AABA:"
    time: 3600
