pipeline {
    agent any
    
    
    stages {
        stage('build') { 
	  steps {
	  dir('angular-e2e'){
	    echo 'building the app'
	    nodejs('Node-10.16.3'){
	        bat 'npm install'
	    	bat 'npm run-script build'
		}
	    }
	  }
        }
	stage('deploy') { 
            steps {
	    dir('angular-e2e'){
	    bat 'docker build -t test -f dev-ops/Dockerfile .'
	    }
	      
                    
            }
        }

	stage('run') { 
            steps {
	       bat 'docker run -p 8000:80 -d test'
                    
            }
        }
    }
 }